# Generated by Django 5.2.4 on 2025-07-07 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(blank=True, max_length=20)),
                ('country_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_fetched', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('format', models.CharField(choices=[('odi', 'ODI'), ('test', 'Test'), ('t20', 'T20'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('role', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('batting_style', models.CharField(blank=True, max_length=100, null=True)),
                ('bowling_style', models.CharField(blank=True, max_length=100, null=True)),
                ('matches', models.IntegerField(blank=True, null=True)),
                ('innings', models.IntegerField(blank=True, null=True)),
                ('runs', models.IntegerField(blank=True, null=True)),
                ('batting_average', models.FloatField(blank=True, null=True)),
                ('strike_rate', models.FloatField(blank=True, null=True)),
                ('fifties', models.IntegerField(blank=True, null=True)),
                ('hundreds', models.IntegerField(blank=True, null=True)),
                ('overs', models.FloatField(blank=True, null=True)),
                ('wickets', models.IntegerField(blank=True, null=True)),
                ('economy', models.FloatField(blank=True, null=True)),
                ('bowling_average', models.FloatField(blank=True, null=True)),
                ('five_wicket_hauls', models.IntegerField(blank=True, null=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cricdata_api.team')),
            ],
        ),
    ]
