# Generated by Django 5.2.4 on 2025-07-08 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_team_id', models.IntegerField(unique=True, verbose_name='External Team ID')),
                ('full_team_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Full Team Name')),
                ('team_abbreviation', models.CharField(blank=True, max_length=20, null=True, verbose_name='Team Abbreviation')),
                ('country_name', models.CharField(max_length=100, verbose_name='Country Name')),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Time Fetched')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_player_id', models.IntegerField(verbose_name='External Player ID')),
                ('player_full_name', models.CharField(max_length=100, verbose_name='Player Full Name')),
                ('format_category', models.CharField(choices=[('odi', 'ODI'), ('test', 'Test'), ('t20', 'T20'), ('unknown', 'Unknown')], default='unknown', max_length=10, verbose_name='Match Format')),
                ('player_role_type', models.PositiveSmallIntegerField(choices=[(1, 'Batsman'), (2, 'Bowler'), (3, 'All-Rounder'), (4, 'Wicket-Keeper'), (5, 'Captain'), (6, 'Vice-Captain')], verbose_name='Player Role')),
                ('is_active_player', models.BooleanField(default=True, verbose_name='Is Currently Active?')),
                ('batting_style_description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Batting Style left/right handed')),
                ('bowling_style_description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bowling Style left/right handed')),
                ('total_matches_played', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Matches Played')),
                ('total_innings_batted', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Innings Batted')),
                ('total_runs_scored', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total Runs Scored')),
                ('career_batting_average', models.FloatField(blank=True, null=True, verbose_name='Batting Average')),
                ('career_strike_rate', models.FloatField(blank=True, null=True, verbose_name='Strike Rate')),
                ('number_of_fifties', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Fifties Scored')),
                ('number_of_hundreds', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Hundreds Scored')),
                ('total_overs_bowled', models.FloatField(blank=True, null=True, verbose_name='Overs Bowled')),
                ('total_wickets_taken', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Wickets Taken')),
                ('bowling_economy_rate', models.FloatField(blank=True, null=True, verbose_name='Bowling Economy')),
                ('bowling_average_score', models.FloatField(blank=True, null=True, verbose_name='Bowling Average')),
                ('number_of_five_wicket_hauls', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='5-Wicket Hauls')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cricdata_api.team', verbose_name='Associated Team')),
            ],
            options={
                'unique_together': {('external_player_id', 'format_category')},
            },
        ),
    ]
