# Generated by Django 5.2.4 on 2025-07-10 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricdata_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
        migrations.AddField(
            model_name='player',
            name='player_associated_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='cricdata_api.team', verbose_name='Associated Team'),
        ),
        migrations.AlterField(
            model_name='player',
            name='batting_style_description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Batting Style (L/R)'),
        ),
        migrations.AlterField(
            model_name='player',
            name='bowling_style_description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bowling Style (L/R)'),
        ),
    ]
