# Generated by Django 5.2.4 on 2025-07-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricdata_api', '0002_alter_team_team_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('player_id', 'format')},
        ),
    ]
