# Generated by Django 5.2.4 on 2025-07-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricdata_api', '0002_remove_player_team_player_player_associated_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='format_category',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, 'test'), (2, 'odi'), (3, 't20')], default=0, verbose_name='Match Format'),
        ),
    ]
